title: BenjaTK
description: My small place in the internet
author:
  twitter: benjatkdev

baseurl: /
url: https://benjatk.com
permalink: /:title
collections:
  posts:
    output: true
    permalink: /blog/:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  posts_limit: 20

twitter:
  username: benjatkdev
  card: summary

logo: /favicon.png

social:
  name: BenjaTK
  links:
    - https://github.com/BenjaTK
    - https://x.com/benjatkdev
    - https://www.reddit.com/user/BenjaTKDev/