title: BenjaTK
description: My small place in the internet
author: BenjaTK

baseurl: /
url: https://benjatk.com
permalink: /:title
collections:
  posts:
    output: true
    permalink: /blog/:title

wikilinks:
  attributes:
    enabled: true
  case:
    'lower case'
  css:
    exclude: []
    name:
      typed: 'typed'
      wiki: 'wiki-link'
      web: 'web-link'
      invalid_wiki: 'invalid-wiki-link'
      embed_container: 'embed-container'
      embed_title: 'embed-title'
      embed_content: 'embed-content'
      embed_link: 'embed-wiki-link'
      embed_image_container: 'embed-image-container'
      embed_image: 'embed-image'
  enabled: true
  exclude: []

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-wikirefs

feed:
  posts_limit: 20

twitter:
  username: benjatkdev
  card: summary

logo: /favicon.png

social:
  name: BenjaTK
  links:
    - https://github.com/BenjaTK
    - https://x.com/benjatkdev
    - https://www.reddit.com/user/BenjaTKDev/
