title: BenjaTK
description: My small place in the internet
author:
  twitter: BenjaTKDev

baseurl: /
url: https://benjatk.com
permalink: /:categories/:year/:month/:day/:title

plugins:
  - jekyll-feed

feed:
  posts_limit: 20

